variables:
  SRC_DIR: "$CI_PROJECT_DIR/python-flask-server"

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $SRC_DIR --dockerfile $SRC_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE
